export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const CHECK_USER_IS_ADMIN_SUCCESS = "CHECK_USER_IS_ADMIN_SUCCESS";
export const LOAD_NOTIFICATION_COUNT_SUCCESS =
  "LOAD_NOTIFICATION_COUNT_SUCCESS";
export const NOTIFICATION_COUNT_DECREMENT = "NOTIFICATION_COUNT_DECREMENT";
